# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('heart_interval', models.IntegerField(default=60)),
                ('record_end', models.IntegerField(default=2)),
                ('file_max_len', models.IntegerField()),
                ('upload_ftp_address', models.CharField(max_length=255)),
                ('upload_ftp_passwd', models.CharField(max_length=255)),
                ('upload_ftp_usr', models.CharField(max_length=255)),
                ('upload_ftp_path', models.CharField(max_length=255)),
                ('update_ftp_address', models.CharField(max_length=255)),
                ('update_ftp_passwd', models.CharField(max_length=255)),
                ('update_ftp_path', models.CharField(max_length=255)),
                ('soft_ver', models.CharField(max_length=255)),
                ('ntpserver', models.CharField(max_length=255)),
                ('uploadfile_time', models.IntegerField()),
                ('config_interval', models.IntegerField(default=720)),
                ('wifi_ssid', models.CharField(max_length=16)),
                ('wifi_psword', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Device_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('powersupply', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=255)),
                ('devicetime', models.CharField(max_length=255)),
                ('storage', models.CharField(max_length=255)),
                ('wifi_db', models.CharField(max_length=255)),
            ],
        ),
    ]
