# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-22 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device_config',
            new_name='DeviceConfig',
        ),
        migrations.RenameModel(
            old_name='Device_status',
            new_name='DeviceStatus',
        ),
    ]
