# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-22 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190422_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='device_id',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='network',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='powersupply',
            field=models.CharField(max_length=1),
        ),
    ]
